version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf 


  frontend:
    container_name: frontend
    image: tmarshfsr/frontend
    build: ./frontendproject
    ports: 
      - target: 3000
        published: 3000

  backend:
    container_name: backend
    image: tmarshfsr/backend
    build: ./backend
    ports: 
      - target: 8080
        published: 8080
    build: ./TaurusBackend

