all:
  vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_user: ubuntu
  children:
    jenkins:
      vars:
        ansible_ssh_private_key_file: '~/.ssh/jenkins-key.pem'
      hosts:
        10.0.1.158:
    prod:
      vars:
        ansible_ssh_private_key_file: '~/.ssh/prod-key.pem'
      hosts:
        10.0.1.58:
    test:
      vars:
        ansible_ssh_private_key_file: '~/.ssh/prod-key.pem'
      hosts:
        10.0.1.230:
